### ISSUE TITLE
Shooter To-Do

### ISSUE THREAD

**Issue by justinyue1643** [OASTEM/Rapid-React-2022#9]
- [X] Create shooter command
- [ ] Test shooter w/ bumpers included
- [ ] Test shooter once mounted on robot
